### ISSUE TITLE
source code for running MMVax

### ISSUE THREAD

**Issue by lsq945** [Supermaxman/MMVax-Stance#2]
Hello, thank you for your work, it is very useful to me. I am a first-year graduate student who has just started NLP. I used the ID you provided to crawl the Twitter data (although the current data volume is only 80% of the original).

Regarding the multi-modal methods mentioned in the experiment of your paper: CLIP_joint, VILT, FLAVA, BT, I tried to use these methods to run the data I crawled, but I encountered some problems. My understanding is that I need to use Twitter data to finetune the multi-modal pre-trained models and evaluate the results.

But unfortunately, I couldn't successfully do this. I don't know how to change the source code of these methods, which is very difficult for me. So, could you please send me a copy of your source code for running the Twitter data. My email is: 3026158913@qq.com
Thank you very much for your work and I look forward to hearing from you. Good luck with your work!

**Comment by Supermaxman** [comment]
Source code is included in this git repo.
